[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
nft_coupon = "REC6VwdAzaaNdrUCWbXmqqN8ryoSAphQkft2BX1P1b1"

[programs.localnet]
nft_coupon = "REC6VwdAzaaNdrUCWbXmqqN8ryoSAphQkft2BX1P1b1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/rz/.config/solana/REC-devnet.json"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
